<?php

namespace AskNicely\Model;

use AskNicely\Exception\ValidationException;
use Illuminate\Database\Eloquent\Model;

class Todo extends Model implements ModelInterface {
    public $timestamps = false;
    protected $table = 'todos';
    protected $primaryKey = 'id';

    protected $attributes = [
        'description' => null,
        'done' => false,
    ];

    protected $fillable = [
        'description',
        'user_id',
        'done',
    ];

    /**
     * @inheritDoc
     * @throws ValidationException
     */
    public function save(array $options = [])
    {
        $this->validateBeforeSave();
        return parent::save($options); // TODO: Change the autogenerated stub
    }

    public function create(array $attributes = [])
    {
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function validateBeforeSave()
    {
        if (!in_array($this->done, [false, true], 1)) {
            throw new ValidationException("'done' can only be either an integer 0 or 1.");
        }
    }
}